/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registroevidencia;

/**
 *
 * @author ALOMIA
 */
public class CrearRegistro extends javax.swing.JFrame {

    /**
     * Creates new form CrearRegistro
     */
    public CrearRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton6 = new javax.swing.JButton();
        backPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        contenedorComponentes = new javax.swing.JPanel();
        idEvidencia = new javax.swing.JTextField();
        referenciaEvidencia = new javax.swing.JTextField();
        aprobado = new javax.swing.JButton();
        noAprobado = new javax.swing.JButton();
        selecinarFecha = new javax.swing.JTextField();
        tipoTrabajo = new javax.swing.JTextField();
        ciudadOperacion = new javax.swing.JTextField();
        fechaRegistroInformacion = new javax.swing.JTextField();
        botonAprobada = new javax.swing.JButton();
        noAprobada = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedorComponentes.setMinimumSize(new java.awt.Dimension(500, 500));
        contenedorComponentes.setPreferredSize(new java.awt.Dimension(500, 500));
        java.awt.GridBagLayout contenedorComponentesLayout = new java.awt.GridBagLayout();
        contenedorComponentesLayout.columnWidths = new int[] {0, 100, 0, 100, 0, 100, 0, 100, 0};
        contenedorComponentesLayout.rowHeights = new int[] {0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0};
        contenedorComponentes.setLayout(contenedorComponentesLayout);

        idEvidencia.setColumns(30);
        idEvidencia.setText("ID: numero contrato");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        contenedorComponentes.add(idEvidencia, gridBagConstraints);

        referenciaEvidencia.setColumns(30);
        referenciaEvidencia.setText("Rf: numero referencia");
        referenciaEvidencia.setMinimumSize(new java.awt.Dimension(700, 50));
        referenciaEvidencia.setName(""); // NOI18N
        referenciaEvidencia.setPreferredSize(new java.awt.Dimension(700, 50));
        referenciaEvidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenciaEvidenciaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        contenedorComponentes.add(referenciaEvidencia, gridBagConstraints);

        aprobado.setText("Registro Aprobado");
        aprobado.setMaximumSize(new java.awt.Dimension(150, 50));
        aprobado.setMinimumSize(new java.awt.Dimension(150, 50));
        aprobado.setName(""); // NOI18N
        aprobado.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        contenedorComponentes.add(aprobado, gridBagConstraints);

        noAprobado.setText("Registro no aprobado");
        noAprobado.setMaximumSize(new java.awt.Dimension(150, 50));
        noAprobado.setMinimumSize(new java.awt.Dimension(150, 50));
        noAprobado.setPreferredSize(new java.awt.Dimension(150, 50));
        noAprobado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noAprobadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contenedorComponentes.add(noAprobado, gridBagConstraints);

        selecinarFecha.setText("Seleccionar fecha ejecucion");
        selecinarFecha.setMaximumSize(new java.awt.Dimension(700, 50));
        selecinarFecha.setMinimumSize(new java.awt.Dimension(700, 50));
        selecinarFecha.setPreferredSize(new java.awt.Dimension(700, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contenedorComponentes.add(selecinarFecha, gridBagConstraints);

        tipoTrabajo.setText("Seleccion tipo de trabajo");
        tipoTrabajo.setMaximumSize(new java.awt.Dimension(700, 50));
        tipoTrabajo.setMinimumSize(new java.awt.Dimension(700, 50));
        tipoTrabajo.setPreferredSize(new java.awt.Dimension(700, 50));
        tipoTrabajo.setSelectionEnd(27);
        tipoTrabajo.setSelectionStart(27);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contenedorComponentes.add(tipoTrabajo, gridBagConstraints);

        ciudadOperacion.setText("Cali, valle");
        ciudadOperacion.setMaximumSize(new java.awt.Dimension(700, 50));
        ciudadOperacion.setMinimumSize(new java.awt.Dimension(700, 50));
        ciudadOperacion.setPreferredSize(new java.awt.Dimension(700, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contenedorComponentes.add(ciudadOperacion, gridBagConstraints);

        fechaRegistroInformacion.setText("25/30/2026");
        fechaRegistroInformacion.setMaximumSize(new java.awt.Dimension(700, 50));
        fechaRegistroInformacion.setMinimumSize(new java.awt.Dimension(700, 50));
        fechaRegistroInformacion.setPreferredSize(new java.awt.Dimension(700, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contenedorComponentes.add(fechaRegistroInformacion, gridBagConstraints);

        botonAprobada.setText("Aprobada");
        botonAprobada.setMaximumSize(new java.awt.Dimension(150, 50));
        botonAprobada.setMinimumSize(new java.awt.Dimension(150, 50));
        botonAprobada.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contenedorComponentes.add(botonAprobada, gridBagConstraints);

        noAprobada.setText("No aprobada");
        noAprobada.setMaximumSize(new java.awt.Dimension(150, 50));
        noAprobada.setMinimumSize(new java.awt.Dimension(150, 50));
        noAprobada.setOpaque(true);
        noAprobada.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contenedorComponentes.add(noAprobada, gridBagConstraints);

        scroll.setPreferredSize(new java.awt.Dimension(574, 500));

        observaciones.setColumns(50);
        observaciones.setRows(10);
        observaciones.setTabSize(10);
        observaciones.setText("Esta es el area de observaciones del componenete");
        observaciones.setMinimumSize(new java.awt.Dimension(275, 200));
        observaciones.setPreferredSize(new java.awt.Dimension(500, 500));
        observaciones.setSelectionEnd(100);
        observaciones.setSelectionStart(100);
        scroll.setViewportView(observaciones);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        contenedorComponentes.add(scroll, gridBagConstraints);

        jPanel1.add(contenedorComponentes);

        backPanel.add(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noAprobadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noAprobadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noAprobadoActionPerformed

    private void referenciaEvidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenciaEvidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenciaEvidenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aprobado;
    private javax.swing.JPanel backPanel;
    private javax.swing.JButton botonAprobada;
    private javax.swing.JTextField ciudadOperacion;
    private javax.swing.JPanel contenedorComponentes;
    private javax.swing.JTextField fechaRegistroInformacion;
    private javax.swing.JTextField idEvidencia;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton noAprobada;
    private javax.swing.JButton noAprobado;
    private javax.swing.JTextArea observaciones;
    private javax.swing.JTextField referenciaEvidencia;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField selecinarFecha;
    private javax.swing.JTextField tipoTrabajo;
    // End of variables declaration//GEN-END:variables
}
