
package evidence.manager;

import evidence.manager.Login;

/**
 *
 * @author ALOMIA
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        nombre = new javax.swing.JTextField();
        apellidos = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        cuidad = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        comprobarEmail = new javax.swing.JTextField();
        nombreEmpresa = new javax.swing.JTextField();
        departamento = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();
        verificarContraseña = new javax.swing.JPasswordField();
        creaRegistro = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        nombre.setForeground(new java.awt.Color(51, 0, 255));
        nombre.setText("nombres:");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        apellidos.setBackground(new java.awt.Color(255, 255, 255));
        apellidos.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        apellidos.setForeground(new java.awt.Color(0, 0, 204));
        apellidos.setText("apellidos:");

        cedula.setBackground(new java.awt.Color(255, 255, 255));
        cedula.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        cedula.setForeground(new java.awt.Color(51, 0, 204));
        cedula.setText("ID usuario:");
        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });

        cuidad.setBackground(new java.awt.Color(255, 255, 255));
        cuidad.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        cuidad.setForeground(new java.awt.Color(51, 0, 204));
        cuidad.setText("Ciudad:");

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        email.setForeground(new java.awt.Color(51, 0, 204));
        email.setText("Email:");

        comprobarEmail.setBackground(new java.awt.Color(255, 255, 255));
        comprobarEmail.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        comprobarEmail.setForeground(new java.awt.Color(51, 0, 204));
        comprobarEmail.setText("Comprobar Email:");
        comprobarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobarEmailActionPerformed(evt);
            }
        });

        nombreEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        nombreEmpresa.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        nombreEmpresa.setForeground(new java.awt.Color(51, 0, 204));
        nombreEmpresa.setText("Empresa:");

        departamento.setBackground(new java.awt.Color(255, 255, 255));
        departamento.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        departamento.setForeground(new java.awt.Color(51, 0, 204));
        departamento.setText("Area Operativa:");

        contraseña.setBackground(new java.awt.Color(255, 255, 255));
        contraseña.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        contraseña.setForeground(new java.awt.Color(51, 0, 204));
        contraseña.setText("jPasswordField1");

        verificarContraseña.setBackground(new java.awt.Color(255, 255, 255));
        verificarContraseña.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        verificarContraseña.setForeground(new java.awt.Color(51, 0, 204));
        verificarContraseña.setText("jPasswordField2");

        creaRegistro.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        creaRegistro.setForeground(new java.awt.Color(51, 0, 204));
        creaRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creaRegistro.setText("crear registro");
        creaRegistro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 204), 2, true));
        creaRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creaRegistroMouseClicked(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(51, 0, 204));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Registro de usario");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nombreEmpresa)
                                    .addComponent(email)
                                    .addComponent(cedula)
                                    .addComponent(nombre)
                                    .addComponent(departamento, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(apellidos)
                                    .addComponent(cuidad)
                                    .addComponent(comprobarEmail)
                                    .addComponent(verificarContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(contraseña)))))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(creaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuidad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comprobarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verificarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(creaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaActionPerformed

    private void comprobarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobarEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprobarEmailActionPerformed

    private void creaRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creaRegistroMouseClicked
        // TODO add your handling code here:  
     
    }//GEN-LAST:event_creaRegistroMouseClicked

    private void apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosActionPerformed

    /**
     * @param args the command line arguments
     */
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidos;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField comprobarEmail;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel creaRegistro;
    private javax.swing.JTextField cuidad;
    private javax.swing.JTextField departamento;
    private javax.swing.JTextField email;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombreEmpresa;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel titulo;
    private javax.swing.JPasswordField verificarContraseña;
    // End of variables declaration//GEN-END:variables
}
