/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evidence.manager;

import javax.swing.JFrame;

/**
 *
 * @author ALOMIA
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        iconoUsuario = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        recordar = new javax.swing.JCheckBox();
        iniciar = new javax.swing.JLabel();
        registro = new javax.swing.JLabel();
        contacto = new javax.swing.JLabel();
        iconoCorreo = new javax.swing.JLabel();
        iconoContraseña = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 150));
        setName("VentanaInicio"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        iconoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio.png"))); // NOI18N
        jPanel1.add(iconoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 608, 180));

        nombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        nombreUsuario.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        nombreUsuario.setForeground(new java.awt.Color(51, 0, 204));
        nombreUsuario.setText("nombre Usuario");
        nombreUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 2, true));
        nombreUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreUsuarioFocusLost(evt);
            }
        });
        jPanel1.add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 230, 40));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        password.setForeground(new java.awt.Color(51, 0, 204));
        password.setText("jPasswordField1");
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 2, true));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 230, 40));

        recordar.setBackground(new java.awt.Color(255, 255, 255));
        recordar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        recordar.setForeground(new java.awt.Color(51, 0, 204));
        recordar.setSelected(true);
        recordar.setText("recordar usuario");
        recordar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        recordar.setBorderPaintedFlat(true);
        jPanel1.add(recordar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        iniciar.setBackground(new java.awt.Color(255, 255, 255));
        iniciar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        iniciar.setForeground(new java.awt.Color(51, 0, 204));
        iniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniciar.setText("iniciar");
        iniciar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));
        iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarMouseClicked(evt);
            }
        });
        jPanel1.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 61, 27));

        registro.setBackground(new java.awt.Color(51, 0, 255));
        registro.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        registro.setForeground(new java.awt.Color(51, 0, 204));
        registro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registro.setText("registrarce");
        registro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 2, true));
        registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroMouseClicked(evt);
            }
        });
        jPanel1.add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 61, 27));

        contacto.setBackground(new java.awt.Color(255, 255, 255));
        contacto.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        contacto.setForeground(new java.awt.Color(51, 0, 204));
        contacto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contacto.setText("¿Problemas para iniciar seccion? Contactenos aqui");
        jPanel1.add(contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 270, 10));

        iconoCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/correo.png"))); // NOI18N
        iconoCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 204), 2, true));
        jPanel1.add(iconoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 47, 40));

        iconoContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contrasena .png"))); // NOI18N
        iconoContraseña.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 204), 2, true));
        jPanel1.add(iconoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 46, 40));

        panelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 380));

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseClicked
        // TODO add your handling code here:
      

    }//GEN-LAST:event_iniciarMouseClicked

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
         String code = password.getText();
        if(password.getText().equals(code)){
            password.setText("");
        }else{
            password.setText(password.getText());
        }
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        
           if(password.getText().equals("")){
                password.setText("*****************");
           }else{
               password.setText(password.getText());
           }
        
    }//GEN-LAST:event_passwordFocusLost

    private void nombreUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreUsuarioFocusLost
        // TODO add your handling code here:
           if(nombreUsuario.getText().equals("")){
                nombreUsuario.setText("nombre Usuario");
           }else{
                nombreUsuario.setText(nombreUsuario.getText());
           }
        
    }//GEN-LAST:event_nombreUsuarioFocusLost

    private void nombreUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreUsuarioFocusGained
        // TODO add your handling code here:
         
         if(nombreUsuario.getText().equals("nombre Usuario") ){
             nombreUsuario.setText("");
                
           }else if(nombreUsuario.getText().equals("") ){
               nombreUsuario.setText("");  
           }else{
               nombreUsuario.setText(nombreUsuario.getText());
           }
    }//GEN-LAST:event_nombreUsuarioFocusGained

    private void registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMouseClicked
        // TODO add your handling code here:
          Registro reg = new Registro();
          reg.setVisible(true);
          Login log = new Login();
          log.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
          
                
    }//GEN-LAST:event_registroMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contacto;
    private javax.swing.JLabel iconoContraseña;
    private javax.swing.JLabel iconoCorreo;
    private javax.swing.JLabel iconoUsuario;
    private javax.swing.JLabel iniciar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreUsuario;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox recordar;
    private javax.swing.JLabel registro;
    // End of variables declaration//GEN-END:variables
}
